### ISSUE TITLE
Using this template does not support language settings from OneTrust

### ISSUE THREAD

**Issue by NsophiaZ** [OneTrustCMP/OneTrust-gtm-template#2]
This template does not support the use of data-document-language="true" setting. Any site that uses a different language from the default ends up with the default language.
Ways to replicate:
- Set template in OneTrust to have multiple languages
- When publishing the script, enable language detection on Scripts -> choose "determine the language from HTML page"
- All sites still use the default language because the data-document-language="true" setting is not included in this template.

**Comment by hubigitt** [comment]
same issue here

**Comment by LCHCAPITALHUMAIN** [comment]
Same here

**Comment by mikeziri** [comment]
Same issue here!
Just upgraded the GTM integration to this Template Tag but just noticed it does not respect the HTML tag <html lang="xx"> explained here: https://onetrustprivacy.my.site.com/cpcustomers/s/article/UUID-7478d3b4-18eb-3ac0-a6fd-fb7ebff9f8dc?language=en_US

One possible solution would be to add possibility of passing data-params via script src URL to `injectScript` API

**Comment by Ruud-Nixon** [comment]
Same issue here! Any idea of when we can expect the template to be updated?

**Comment by rodricels** [comment]
Same problem here, opened a ticket to Onetrust. I imagine that @schavvaOt is an employee of onetrust.

**Comment by ShayOluOT** [comment]
Hey all! 

Just an update, we've acknowledged this and working on an update to the template within our next release! Will drop a comment here and will update our release notes.

Shay

**Comment by OwenFromLaunch** [comment]
We have a multi-national client that operates across the EU in 12 different languages, moving to this tag to manage consent mode has the same issue. Can we have an idea of timelines please for this update to the tag?

**Comment by NsophiaZ** [comment]
Hi guys, here is a workaround I'm using for now. Let me know if this works or if you have any questions. Also open to suggestions:

- Configure Google Consent Mode in the geolocation Rules. After saving the changes in the geolocation rule. It is necessary to republish the scripts you want to have updated.
- In the GTM container settings, enable consent overview.
- This gives you an overview page to manage all google tags consent in one place. After enabling this you will get the consent overview option in GTM Tags Tab.
- Using the consent Overview page, configure consent for all tags that need google consent. One Important thing to note, don’t require google consent for any consent related tags. Those should always fire to allow for consent to be collected.
- **This step is the work around. If oneTrust’s template was working. We would just directly add OneTrust’s “OneTrust CMP” GTM template and configure that. Because it currently does not support languages. Using Simo's template is a workaround to establish the consent default.**
- Add simo’s Consent Mode (Google tags) template. Search for “Consent Mode (Google tags)” in search gallery option.
- Using Simo’s Tag template, create a new tag and configure the “Default” consent settings tag and configure other settings and advanced settings as required on your site. Trigger this based off the **consent initialization – All Pages** trigger. In the region option, you can set either, EEA, or All for all countries, or use a country code target a specific country.
- OneTrust will make the Google Consent update when a user’s consent is updated. Go through different pages and confirm consent is persisted through multiple pages.
- Preview and test as needed.

Thanks!

**Comment by rbomhof** [comment]
We are also interested in what the timeline might be for this update. Thank you!

**Comment by ShayOluOT** [comment]
Following this up we're already in the sprint this is being developed so it'll be within the next couple of weeks, in the 202404.1 release - to find your specific environment please refer to this my.onetrust document https://my.onetrust.com/s/article/Scheduled-Maintenance.

Please feel free to comment if you have any more additional questions

Shay

**Comment by mikeziri** [comment]
Thank you!
If you can, please comment here when it's released so we are notified.

**Comment by phildpearce** [comment]
I have posted a Custom HTML work-around here:
https://measuremindsgroup.com/why-you-should-not-use-the-onetrust-gtm-template#script-solution

Hopefully, Onetrust will update getLanguage() within otSDKStub.js to support _both_ ?language=EN and data-document-language=EN, so that it can be then added to the native GTM template.

```
function getLanguage() {
return document.querySelector("script[src*='otSDKStub.js']").getStubQueryParam("language") || 
document.querySelector("script[data-domain-script]").getAttribute("data-document-language");
}
```

```
<script>
    (function(){
        var gtm_onetrust_id = "fff8df06-1dd2-491b-88f6-01cae248cd17"; // Replace with your domainID here
        var _ot = document.createElement("script");
            _ot.setAttribute("data-document-language", "true"); // Enabled page language (not browser language)
            _ot.type = "text/javascript";
            _ot.charset = "UTF-8";
            _ot.async = true;
            _ot.src = "https://cdn.cookielaw.org/scripttemplates/otSDKStub.js";
        var _s = document.getElementsByTagName("script")[0]; _s.parentNode.insertBefore(_ot, _s);
    })();
</script>
```

**Comment by wardow-it** [comment]
Hi, I have been facing the same issue with the language. Please leave a comment when it is fixed

**Comment by rbomhof** [comment]
@ShayOluOT Any updates on this one?

**Comment by jahilldev** [comment]
Hi there,

I've also encountered this issue. Is there any movement? We'd really like to use the community template, but we also want to specify a language override per domain.

**Comment by phildpearce** [comment]
Yah! 👍 

This '&data-document-language=true' update finally rollout on May 24th (4days ago).

![image](https://github.com/OneTrustCMP/OneTrust-gtm-template/assets/7198778/86c57039-d90a-4bf2-8947-cb00101ba7e2)

![image](https://github.com/OneTrustCMP/OneTrust-gtm-template/assets/7198778/36a79fbc-b71c-49c1-8525-c248e8a10df4)

https://github.com/OneTrustCMP/OneTrust-gtm-template/commits/master/metadata.yaml

**Comment by NsophiaZ** [comment]
Hi @phildpearce/ @schavvaOt , Can you please confirm that you have tested this and it worked for you? I still get the same issue on all languages except English.

**Comment by ShayOluOT** [comment]
@namugerwasophia please make sure, have you published to version 5.1 or higher?

**Comment by NsophiaZ** [comment]
That works. Thank you so much!

**Comment by Aiste-Pet** [comment]
@ShayOluOT Hey, I have published 202405.2.0, accepted the new template on GTM and have Determine the language from HTML page setting on scripts enabled, but I still don't seem to be getting the appropriate language. We also have the language setting on our pages and it used to work before we transferred to GTM. Is there anything else I need to make this work?

**Comment by schavvaOt** [comment]
> @ShayOluOT Hey, I have published 202405.2.0, accepted the new template on GTM and have Determine the language from HTML page setting on scripts enabled, but I still don't seem to be getting the appropriate language. We also have the language setting on our pages and it used to work before we transferred to GTM. Is there anything else I need to make this work?

@Aiste-Pet Ideally it should work. How are you setting language on your page? A code snippet or test page would be helpful.

**Comment by Aiste-Pet** [comment]
@ShayOluOT we have set the language in HTML tag:
![image](https://github.com/OneTrustCMP/OneTrust-gtm-template/assets/105724465/ecaa6e6f-5177-419e-b7ee-6f3c40a2a672)
It wasn't long ago we made this change and we saw that this helped the language setting on cookie banners. But soon after due to Google Consent Mode we decided to move to GTM OneTrust approach and this is when it stopped working.

**Comment by wardow-it** [comment]
@ShayOluOT Hello, I have imported the new OneTrustCMP template and enabled the Determine the language from the HTML page in addition to this how can I use the language variable in the new template? I was using the HTML script tag before as shown here. 
![image](https://github.com/OneTrustCMP/OneTrust-gtm-template/assets/121867717/b17b3f90-76ad-4c3a-b60d-f71e9c276d4d)
Please let me know how I can enable the language variable to get the desired language cookie banner.

**Comment by mikeziri** [comment]
Can confirm.
Everything working on the new Production scripts + GTM template with Language HTML Detection active.
